language: c

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: II6jU3Pf/mRIAWM4ns+pPjuSJQcecs02f3KXibwtYohBt8f9SCD2yxR+uw5V1f1tyXegh139vI7QyBn9IH1z3NHys0yOu2/TBAoDWa60SBgjTEBqG2akPC77hz9D40m9upIF60d1cLkF9r55SL1lU7wq4Fb8gCX2G7HDki7Jjqw=

install:
  - sudo apt-add-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu `lsb_release -cs`/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-add-repository -y ppa:marutter/c2d4u
  - sudo apt-get update
  - sudo apt-get install r-base-dev r-cran-devtools r-cran-rcpp pandoc pandoc-citeproc
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - export R_VIGNETTE=Rd2roxygen.html
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"

